/**
 * Pagination TesterLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Transaction, transactionSchema } from './transaction';

export interface TransactionsOffset {
  data?: Transaction[];
}

export const transactionsOffsetSchema: Schema<TransactionsOffset> = object({
  data: ['data', optional(array(lazy(() => transactionSchema)))],
});
