/**
 * Pagination TesterLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { array, lazy, object, optional, Schema } from '../schema';
import { Links, linksSchema } from './links';
import { Transaction, transactionSchema } from './transaction';

export interface TransactionsLinked {
  data?: Transaction[];
  links?: Links;
}

export const transactionsLinkedSchema: Schema<TransactionsLinked> = object({
  data: ['data', optional(array(lazy(() => transactionSchema)))],
  links: ['links', optional(lazy(() => linksSchema))],
});
