/**
 * Pagination TesterLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import { number, object, optional, Schema, string } from '../schema';

export interface Transaction {
  id?: string;
  amount?: number;
  timestamp?: string;
}

export const transactionSchema: Schema<Transaction> = object({
  id: ['id', optional(string())],
  amount: ['amount', optional(number())],
  timestamp: ['timestamp', optional(string())],
});
