/**
 * Pagination TesterLib
 *
 * This file was automatically generated by APIMATIC v3.0 ( https://www.apimatic.io ).
 */

import {
  array,
  lazy,
  nullable,
  object,
  optional,
  Schema,
  string,
} from '../schema';
import { Transaction, transactionSchema } from './transaction';

export interface TransactionsCursored {
  data?: Transaction[];
  /** Cursor for the next page of results. */
  nextCursor?: string | null;
}

export const transactionsCursoredSchema: Schema<TransactionsCursored> = object({
  data: ['data', optional(array(lazy(() => transactionSchema)))],
  nextCursor: ['nextCursor', optional(nullable(string()))],
});
